In [1]:
print('fit a model with', 11, 'variables')


fit a model with 11 variables


In [4]:
3 + 5

8

In [1]:
x = [3 , 4 ,5]
x

[3, 4, 5]

In [2]:
y = [6, 7, 8]
x + y

[3, 4, 5, 6, 7, 8]

In [3]:
import numpy as np

In [6]:
x = np.array([3, 4 ,5])
y = np.array([6, 7, 8])
x + y

array([ 9, 11, 13])

In [8]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [9]:
x.ndim

2

In [10]:
x.dtype

dtype('int64')

In [11]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [12]:
x.shape

(2, 2)

In [13]:
x.sum()

10

In [14]:
np.sum(x)

10

In [15]:
## Tuple are in just ()

In [16]:
x = np.random.normal(size = 50)
x

array([ 0.92553264,  1.25326011, -0.00438479, -1.35425658, -1.87560504,
        0.24084272, -0.46904552,  0.88635812,  0.66594661,  1.72643391,
        0.77724482, -2.31644982,  1.82534115,  0.29734342,  0.23385291,
       -1.5952124 , -0.39686997, -0.18500245, -0.06183262, -2.42910758,
        0.70967124,  0.53794936, -0.37244126, -1.11362408,  1.91293717,
        1.59022185, -0.64502338,  0.33777593, -0.10356453, -0.1268046 ,
        0.10057462,  1.12505501,  2.46594096, -0.22670232,  0.83182915,
       -0.02088742,  0.55983538, -0.85908896,  2.0474557 ,  0.59224578,
        0.00443378, -0.73047773,  0.73224048,  1.58822474, -0.4786542 ,
       -0.68135496, -0.643416  ,  0.91652828, -0.97242945,  0.25063868])

In [17]:
y=  x + np.random.normal(loc = 50, scale = 1, size = 50)

In [18]:
y

array([51.56930091, 49.74191712, 48.34281513, 48.70454198, 47.20607441,
       50.21761408, 51.37325467, 51.54236234, 51.51668875, 50.70027647,
       48.83401043, 47.89084314, 52.55375637, 50.04946887, 51.23981788,
       48.9536034 , 49.04871565, 50.41903882, 50.27287251, 47.62537374,
       49.33722471, 48.43156227, 49.09040985, 49.54039765, 50.30865293,
       51.48111293, 49.99984166, 48.57797454, 49.60695022, 50.29671423,
       49.02721084, 51.82658688, 52.31707197, 49.270594  , 51.86543731,
       48.54584278, 51.50401695, 50.41656194, 52.19755472, 50.40385154,
       49.78943211, 48.58779229, 50.14079409, 51.55348975, 50.28178013,
       49.02585441, 49.75125243, 49.92241223, 49.3966112 , 49.76545608])

In [19]:
np.corrcoef(x, y)

array([[1.        , 0.71366883],
       [0.71366883, 1.        ]])

In [20]:
print(np.random.normal(scale=5,size=2))
print(np.random.normal(scale=5,size=2))

[0.43728399 1.17614834]
[-0.11305064  0.28610587]


In [ ]:
rng = np.random.default_rng(28)
print(rng.normal(scale=5,size=2))
rng2 = np.random.default_rng(28)
print(rng2.normal(scale=5,size=2)